version: "3"
services:
  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  node-server-container:
    build: .
    env_file: 
      - .env
    depends_on:
      - mongo-db
  
  mongo-db:
    volumes:
      - mongo-db:/data/db:rw
    image: mongo
    env_file: 
      - .env
    restart: always

  redis-store:
    image: redis

volumes:
  mongo-db: