version: "3"
services:
  node-server-container:
    build:
      context: .
      args: 
        NODE_ENV: development
    volumes:
      - ./:/app:ro
      - /app/node_modules
    command: npm run dev